// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nigeria.Data;

#nullable disable

namespace nigeria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240929182422_SeedStates")]
    partial class SeedStates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("nigeria.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("double");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Governor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 1171.0,
                            Capital = "Ikeja",
                            Governor = "Babajide Sanwo-Olu",
                            Name = "Lagos",
                            Population = 14210000L,
                            Region = "South-West"
                        },
                        new
                        {
                            Id = 2,
                            Area = 20131.0,
                            Capital = "Kano",
                            Governor = "Abba Kabir Yusuf",
                            Name = "Kano",
                            Population = 11037920L,
                            Region = "North-West"
                        },
                        new
                        {
                            Id = 3,
                            Area = 4844.0,
                            Capital = "Awka",
                            Governor = "Charles Chukwuma Soludo",
                            Name = "Anambra",
                            Population = 5612000L,
                            Region = "South-East"
                        },
                        new
                        {
                            Id = 4,
                            Area = 11077.0,
                            Capital = "Port Harcourt",
                            Governor = "Siminalayi Fubara",
                            Name = "Rivers",
                            Population = 7191000L,
                            Region = "South-South"
                        },
                        new
                        {
                            Id = 5,
                            Area = 28454.0,
                            Capital = "Ibadan",
                            Governor = "Seyi Makinde",
                            Name = "Oyo",
                            Population = 7800000L,
                            Region = "South-West"
                        },
                        new
                        {
                            Id = 6,
                            Area = 6320.0,
                            Capital = "Umuahia",
                            Governor = "Okezie Ikpeazu",
                            Name = "Abia",
                            Population = 3643000L,
                            Region = "South-East"
                        },
                        new
                        {
                            Id = 7,
                            Area = 36917.0,
                            Capital = "Yola",
                            Governor = "Ahmadu Umaru Fintiri",
                            Name = "Adamawa",
                            Population = 4485000L,
                            Region = "North-East"
                        },
                        new
                        {
                            Id = 8,
                            Area = 7081.0,
                            Capital = "Uyo",
                            Governor = "Umo Eno",
                            Name = "Akwa Ibom",
                            Population = 5540000L,
                            Region = "South-South"
                        },
                        new
                        {
                            Id = 9,
                            Area = 4844.0,
                            Capital = "Awka",
                            Governor = "Charles Chukwuma Soludo",
                            Name = "Anambra",
                            Population = 5612000L,
                            Region = "South-East"
                        },
                        new
                        {
                            Id = 10,
                            Area = 45837.0,
                            Capital = "Bauchi",
                            Governor = "Bala Mohammed",
                            Name = "Bauchi",
                            Population = 6555000L,
                            Region = "North-East"
                        },
                        new
                        {
                            Id = 11,
                            Area = 10773.0,
                            Capital = "Yenagoa",
                            Governor = "Douye Diri",
                            Name = "Bayelsa",
                            Population = 2325000L,
                            Region = "South-South"
                        },
                        new
                        {
                            Id = 12,
                            Area = 34059.0,
                            Capital = "Makurdi",
                            Governor = "Hyacinth Alia",
                            Name = "Benue",
                            Population = 5339000L,
                            Region = "North-Central"
                        },
                        new
                        {
                            Id = 13,
                            Area = 70698.0,
                            Capital = "Maiduguri",
                            Governor = "Babagana Umara Zulum",
                            Name = "Borno",
                            Population = 5883000L,
                            Region = "North-East"
                        },
                        new
                        {
                            Id = 14,
                            Area = 20156.0,
                            Capital = "Calabar",
                            Governor = "Bassey Otu",
                            Name = "Cross River",
                            Population = 3785000L,
                            Region = "South-South"
                        },
                        new
                        {
                            Id = 15,
                            Area = 17898.0,
                            Capital = "Asaba",
                            Governor = "Sheriff Oborevwori",
                            Name = "Delta",
                            Population = 5714000L,
                            Region = "South-South"
                        },
                        new
                        {
                            Id = 16,
                            Area = 5533.0,
                            Capital = "Abakaliki",
                            Governor = "Francis Nwifuru",
                            Name = "Ebonyi",
                            Population = 2905000L,
                            Region = "South-East"
                        },
                        new
                        {
                            Id = 17,
                            Area = 17802.0,
                            Capital = "Benin City",
                            Governor = "Godwin Obaseki",
                            Name = "Edo",
                            Population = 4705000L,
                            Region = "South-South"
                        },
                        new
                        {
                            Id = 18,
                            Area = 6353.0,
                            Capital = "Ado Ekiti",
                            Governor = "Biodun Oyebanji",
                            Name = "Ekiti",
                            Population = 3314000L,
                            Region = "South-West"
                        },
                        new
                        {
                            Id = 19,
                            Area = 7161.0,
                            Capital = "Enugu",
                            Governor = "Peter Mbah",
                            Name = "Enugu",
                            Population = 4354000L,
                            Region = "South-East"
                        },
                        new
                        {
                            Id = 20,
                            Area = 18768.0,
                            Capital = "Gombe",
                            Governor = "Inuwa Yahaya",
                            Name = "Gombe",
                            Population = 3102000L,
                            Region = "North-East"
                        },
                        new
                        {
                            Id = 21,
                            Area = 5530.0,
                            Capital = "Owerri",
                            Governor = "Hope Uzodinma",
                            Name = "Imo",
                            Population = 5410000L,
                            Region = "South-East"
                        },
                        new
                        {
                            Id = 22,
                            Area = 23154.0,
                            Capital = "Dutse",
                            Governor = "Umar Namadi",
                            Name = "Jigawa",
                            Population = 5533000L,
                            Region = "North-West"
                        },
                        new
                        {
                            Id = 23,
                            Area = 46053.0,
                            Capital = "Kaduna",
                            Governor = "Uba Sani",
                            Name = "Kaduna",
                            Population = 8117000L,
                            Region = "North-West"
                        },
                        new
                        {
                            Id = 24,
                            Area = 24192.0,
                            Capital = "Katsina",
                            Governor = "Dikko Radda",
                            Name = "Katsina",
                            Population = 8418000L,
                            Region = "North-West"
                        },
                        new
                        {
                            Id = 25,
                            Area = 36800.0,
                            Capital = "Birnin Kebbi",
                            Governor = "Nasir Idris",
                            Name = "Kebbi",
                            Population = 4418000L,
                            Region = "North-West"
                        },
                        new
                        {
                            Id = 26,
                            Area = 29333.0,
                            Capital = "Lokoja",
                            Governor = "Yahaya Bello",
                            Name = "Kogi",
                            Population = 4388000L,
                            Region = "North-Central"
                        },
                        new
                        {
                            Id = 27,
                            Area = 36825.0,
                            Capital = "Ilorin",
                            Governor = "AbdulRahman AbdulRazaq",
                            Name = "Kwara",
                            Population = 3361000L,
                            Region = "North-Central"
                        },
                        new
                        {
                            Id = 28,
                            Area = 27117.0,
                            Capital = "Lafia",
                            Governor = "Abdullahi Sule",
                            Name = "Nasarawa",
                            Population = 2438000L,
                            Region = "North-Central"
                        },
                        new
                        {
                            Id = 29,
                            Area = 76363.0,
                            Capital = "Minna",
                            Governor = "Mohammed Umaru Bago",
                            Name = "Niger",
                            Population = 5384000L,
                            Region = "North-Central"
                        },
                        new
                        {
                            Id = 30,
                            Area = 16762.0,
                            Capital = "Abeokuta",
                            Governor = "Dapo Abiodun",
                            Name = "Ogun",
                            Population = 4968000L,
                            Region = "South-West"
                        },
                        new
                        {
                            Id = 31,
                            Area = 15500.0,
                            Capital = "Akure",
                            Governor = "Rotimi Akeredolu",
                            Name = "Ondo",
                            Population = 4733000L,
                            Region = "South-West"
                        },
                        new
                        {
                            Id = 32,
                            Area = 9251.0,
                            Capital = "Oshogbo",
                            Governor = "Ademola Adeleke",
                            Name = "Osun",
                            Population = 4202000L,
                            Region = "South-West"
                        },
                        new
                        {
                            Id = 33,
                            Area = 30609.0,
                            Capital = "Jos",
                            Governor = "Caleb Mutfwang",
                            Name = "Plateau",
                            Population = 4823000L,
                            Region = "North-Central"
                        },
                        new
                        {
                            Id = 34,
                            Area = 25832.0,
                            Capital = "Sokoto",
                            Governor = "Ahmed Aliyu",
                            Name = "Sokoto",
                            Population = 5106000L,
                            Region = "North-West"
                        },
                        new
                        {
                            Id = 35,
                            Area = 54473.0,
                            Capital = "Jalingo",
                            Governor = "Agbu Kefas",
                            Name = "Taraba",
                            Population = 3386000L,
                            Region = "North-East"
                        },
                        new
                        {
                            Id = 36,
                            Area = 45863.0,
                            Capital = "Damaturu",
                            Governor = "Mai Mala Buni",
                            Name = "Yobe",
                            Population = 2922000L,
                            Region = "North-East"
                        },
                        new
                        {
                            Id = 37,
                            Area = 39262.0,
                            Capital = "Gusau",
                            Governor = "Dauda Lawal",
                            Name = "Zamfara",
                            Population = 4876000L,
                            Region = "North-West"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
